# Projekt: 19. century stuffs
# Autor: Lukáš Kovář
# Datum: 19.03.2020

CC=gcc
CFLAGS= -std=c99 -pedantic -Wall -Wextra -g

hello: hello.c
	$(CC) $(CFLAGS) hello.c -o hello

prvocisla: prvocisla.c
	$(CC) $(CFLAGS) prvocisla.c -o prvocisla

